cities:
  - city: bogota
    display_name: Bogotá
    department: Cundinamarca
    latitude: 4.7110
    longitude: -74.0721
  - city: medellin
    display_name: Medellín
    department: Antioquia
    latitude: 6.2442
    longitude: -75.5812
  - city: barranquilla
    display_name: Barranquilla
    department: Atlántico
    latitude: 10.9685
    longitude: -74.7813
  - city: cali
    display_name: Cali
    department: Valle del Cauca
    latitude: 3.4516
    longitude: -76.5320
  - city: villavicencio
    display_name: Villavicencio
    department: Meta
    latitude: 4.1420
    longitude: -73.6266
